name: gflower
channels:
- defaults
- conda-forge
dependencies:
- python=3.8.12
- pip
- patchelf
- git
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - numpy==1.22
    - gym==0.23.1
    - mujoco_py==2.1.2.14
    - matplotlib==3.3.4
    - torch==1.9.1+cu111
    - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
    - minari[hf]
    - gymnasium==1.0.0
    - h5py==3.11.0
    - einops==0.8.0
    - git+https://github.com/cython/cython.git@3.0.0a10
    - scipy==1.10.1
    - pot==0.9.5
    - tensorboard
    - tyro
    - typed-argument-parser==1.10.1
